name: CI - MSVC, GCC & Clang

on: [push]

jobs:
  build_windows_linux:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Release, Debug]
        cxx: [default, g++, clang++]
        exclude:
          - os: windows-latest
            cxx: g++
          - os: windows-latest
            cxx: clang++
          - os: ubuntu-latest
            cxx: default

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      env:
        CXX: ${{ matrix.cxx != 'default' && matrix.cxx || '' }}
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C ${{ matrix.build_type }}
